shell = "zsh"

[plugins]

# Fast syntax highlighting
# - Faster than traditional zsh-syntax-highlighting
# - Better syntax recognition
# - Multiple themes
# - Regexp-based highlighting
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# Fish-like autosuggestions
# - Shows command suggestions as you type
# - Uses history and completions
# - Can be accepted with right arrow
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# Enhanced tab completion with fzf
# - Replaces default completion with fzf interface
# - Shows previews for files/commands
# - Group support for better organization
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# Modern git operations with fzf
# Usage:
# - ga: interactive git add with preview
# - glo: interactive git log
# - gi: interactive .gitignore generator
# - gd: interactive git diff
[plugins.forgit]
github = "wfxr/forgit"

# Better history search with fzf
# - More powerful than CTRL-R
# - Shows preview of full commands
# - Fuzzy search through history
[plugins.fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"

# Additional completions
# - Adds thousands of completions
# - Works with fzf-tab
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
